package entities;
// Generated Sep 19, 2012 1:13:50 PM by Hibernate Tools 3.2.1.GA



/**
 * AppointType generated by hbm2java
 */
public class AppointType  implements java.io.Serializable {


     private Integer typeid;
     private String type;

    public AppointType() {
    }

    public AppointType(String type) {
       this.type = type;
    }
   
    public Integer getTypeid() {
        return this.typeid;
    }
    
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


