package entities;
// Generated Sep 17, 2012 11:22:58 AM by Hibernate Tools 3.2.1.GA



/**
 * Dosage generated by hbm2java
 */
public class Dosage  implements java.io.Serializable {


     private String shortcut;
     private String mapped;

    public Dosage() {
    }

    public Dosage(String shortcut, String mapped) {
       this.shortcut = shortcut;
       this.mapped = mapped;
    }
   
    public String getShortcut() {
        return this.shortcut;
    }
    
    public void setShortcut(String shortcut) {
        this.shortcut = shortcut;
    }
    public String getMapped() {
        return this.mapped;
    }
    
    public void setMapped(String mapped) {
        this.mapped = mapped;
    }




}


