package entities;
// Generated Sep 23, 2012 9:25:44 AM by Hibernate Tools 3.2.1.GA



/**
 * LabtypeDetailedinv generated by hbm2java
 */
public class LabtypeDetailedinv  implements java.io.Serializable {


     private Integer labtypeMaintestId;
     private int labtypeId;
     private int detailedInvId;

    public LabtypeDetailedinv() {
    }

    public LabtypeDetailedinv(int labtypeId, int detailedInvId) {
       this.labtypeId = labtypeId;
       this.detailedInvId = detailedInvId;
    }
   
    public Integer getLabtypeMaintestId() {
        return this.labtypeMaintestId;
    }
    
    public void setLabtypeMaintestId(Integer labtypeMaintestId) {
        this.labtypeMaintestId = labtypeMaintestId;
    }
    public int getLabtypeId() {
        return this.labtypeId;
    }
    
    public void setLabtypeId(int labtypeId) {
        this.labtypeId = labtypeId;
    }
    public int getDetailedInvId() {
        return this.detailedInvId;
    }
    
    public void setDetailedInvId(int detailedInvId) {
        this.detailedInvId = detailedInvId;
    }




}


