package entities;
// Generated Sep 24, 2012 7:21:11 PM by Hibernate Tools 3.2.1.GA



/**
 * PossibleinvResults generated by hbm2java
 */
public class PossibleinvResults  implements java.io.Serializable {


     private Integer posinvResultId;
     private String posinvResult;

    public PossibleinvResults() {
    }

    public PossibleinvResults(String posinvResult) {
       this.posinvResult = posinvResult;
    }
   
    public Integer getPosinvResultId() {
        return this.posinvResultId;
    }
    
    public void setPosinvResultId(Integer posinvResultId) {
        this.posinvResultId = posinvResultId;
    }
    public String getPosinvResult() {
        return this.posinvResult;
    }
    
    public void setPosinvResult(String posinvResult) {
        this.posinvResult = posinvResult;
    }




}


