package entities;
// Generated Sep 19, 2012 1:13:50 PM by Hibernate Tools 3.2.1.GA



/**
 * Qualification generated by hbm2java
 */
public class Qualification  implements java.io.Serializable {


     private Integer quid;
     private String qualification;
     private String startyear;
     private String endyear;
     private String institution;
     private String staffid;

    public Qualification() {
    }

	
    public Qualification(String qualification, String institution, String staffid) {
        this.qualification = qualification;
        this.institution = institution;
        this.staffid = staffid;
    }
    public Qualification(String qualification, String startyear, String endyear, String institution, String staffid) {
       this.qualification = qualification;
       this.startyear = startyear;
       this.endyear = endyear;
       this.institution = institution;
       this.staffid = staffid;
    }
   
    public Integer getQuid() {
        return this.quid;
    }
    
    public void setQuid(Integer quid) {
        this.quid = quid;
    }
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }
    public String getStartyear() {
        return this.startyear;
    }
    
    public void setStartyear(String startyear) {
        this.startyear = startyear;
    }
    public String getEndyear() {
        return this.endyear;
    }
    
    public void setEndyear(String endyear) {
        this.endyear = endyear;
    }
    public String getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(String institution) {
        this.institution = institution;
    }
    public String getStaffid() {
        return this.staffid;
    }
    
    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }




}


